In [1]:
#Numpy is linear algebra library for Python
#numpy arrays come in 2 flavors: vectors and matrices
#vectors: 1d array
#matrix: 2 d array, can still have 1 row or 1 coluimn


In [3]:
#Numpy SArrays
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np
np.array(my_list)
#array as container for the list

NameError: name 'my_list' is not defined

In [3]:
my_matrice = [[1,2,3],
              [4,5,6],[7,8,9]]
np.array(my_matrice)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#np.arrange() similar to range function
np.arange(0,10) 
#up to but not including 10
1 

1

In [5]:

#get even number, from 0 to 10 with step of 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
#generate array of zeros 5x5 array
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
#generate array of ones 2x3 arrays
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(0,5,5)
#print 1 bracket => 1 dimension
#(start,stop, 10 evenly point)
#srpead from start to stop with  

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [9]:
#create identity matrix
np.eye(4)
#diagonal of 1 and every thing else is 0, take 1 argument because it muist be a square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
#create arrays of random number
# create a 1d array of random number
np.random.rand(5)

array([0.06336086, 0.60661774, 0.32962025, 0.9669822 , 0.76131546])

In [12]:
np.random.rand(4,5)
#create random  number in a 4x5 matrices

array([[0.62436559, 0.86518053, 0.50433126, 0.10218285, 0.58829542],
       [0.28409182, 0.28191394, 0.23549435, 0.43511788, 0.4119289 ],
       [0.72544919, 0.00367668, 0.45082833, 0.71777272, 0.45998343],
       [0.57226711, 0.50758885, 0.10876399, 0.65250196, 0.3720823 ]])

In [15]:
#randInt low >= input, high < input , size = size of array - vectors
#randint(low, high)
np.random.randint(1,100,25)
#create an array of 25 elemnt random from >=1 to  < 100

array([76, 16, 26, 48, 26, 82, 50, 80, 83,  9, 70, 15, 39, 40, 37, 97, 97,
        4, 43, 97, 80, 97, 40,  1, 43])

In [17]:
arr = np.arange(25)
arr
#generating array from to 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
rarr = np.random.randint(0,50,10)
rarr

array([26, 44, 29, 11, 38, 48, 12, 43,  7, 37])

In [22]:
#reshape method, return array with new shap
arr.reshape(5,5)
#number of row * number of collumn = num of element
#reshape into a 5x5 array
#error if cant fill up completely


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
#find max value in array
arr.max()

24

In [25]:
arr.min()

0

In [27]:
rarr.argmax() #l;ocation of max value

5

In [28]:
rarr.max()

48

In [30]:
arr.shape 
#arr is 1 dimennsional vector


(25,)

In [33]:
sarr = arr.reshape(5,5)
sarr.shape


(5, 5)