In [1]:
#Numpy is linear algebra library for Python
#numpy arrays come in 2 flavors: vectors and matrices
#vectors: 1d array
#matrix: 2 d array, can still have 1 row or 1 coluimn


In [3]:
#Numpy SArrays
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
import numpy as np
np.array(my_list)
#array as container for the list

array([1, 2, 3])

In [8]:
my_matrice = [[1,2,3],
              [4,5,6],[7,8,9]]
np.array(my_matrice)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#np.arrange() similar to range function
np.arange(0,10) 
#up to but not including 10
1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:

#get even number, from 0 to 10 with step of 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
#generate array of zeros 5x5 array
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
#generate array of ones 2x3 arrays
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0,5,5)
#print 1 bracket => 1 dimension
#(start,stop, 10 evenly point)
#srpead from start to stop with  

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [27]:
#create identity matrix
np.eye(4)
#diagonal of 1 and every thing else is 0, take 1 argument because it muist be a square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])